spring.application.name=billing-service
server.port=8083

#spring.cloud.config.enabled=false
spring.config.import=optional:configserver:http://localhost:9999

management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
resilience4j.circuitbreaker.instances.customerServiceCB.register-health-indicator=true
