spring.application.name=config-service
server.port=9999
spring.cloud.config.server.git.uri=E:\\auto_formation\\Dev_JAVA\\ecommerce-micro-app\\config-repo
spring.cloud.config.server.git.default-label=master